[build]
#target = "riscv32imc-esp-espidf"
target = "xtensa-esp32-espidf"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
# runner = "espflash --monitor" # Select this runner for espflash v1.x.x
rustflags = ["--cfg", "espidf_time64", "-C", "default-linker-libraries"]

runner = "espflash flash --monitor" # Select this runner for espflash v2.x.x
[target.xtensa-esp32-espidf]
linker = "ldproxy"
# runner = "espflash --monitor" # Select this runner for espflash v1.x.x
runner = "espflash flash --monitor"                                      # Select this runner for espflash v2.x.x
rustflags = ["--cfg", "espidf_time64", "-C", "default-linker-libraries"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
# Note: these variables are not used when using pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = { value = "tag:v5.2.2" }
ESP_IDF_SDKCONFIG_DEFAULTS = "sdkconfig.defaults.esp32"
#ESP_IDF_SDKCONFIG_DEFAULTS = "sdkconfig.defaults.esp"
